http:
  routers:
    authelia-router:
      rule: "Host(`auth.gusbus.co.za`)"
      service: authelia-service
      entryPoints:
        - web
      middlewares:
        - secure-headers

    admin-router:
      rule: "Host(`admin.gusbus.co.za`)"
      service: hello-service
      entryPoints:
        - web
      middlewares:
        - secure-headers
        - authelia-guard

  services:
    authelia-service:
      loadBalancer:
        servers:
          - url: "http://authelia:9091"

    hello-service:
      loadBalancer:
        servers:
          - url: "http://domain-router:8080"

  middlewares:
    secure-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"

    authelia-guard:
      forwardAuth:
        address: "http://authelia:9091/api/authz/forward-auth"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Name"
          - "Remote-Email"
